name: Build 360P2 Printer Firmware (MT7628)

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/openwrt/sdk:22.03.5-ramips-mt76x8  # 使用官方镜像
      options: --user root

    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        path: openwrt-src

    - name: 定位SDK目录
      id: find-sdk
      run: |
        SDK_DIR="/builder"
        if [ ! -d "$SDK_DIR" ]; then
          echo "::error::SDK目录不存在: $SDK_DIR"
          ls -la /
          exit 1
        fi
        echo "SDK_DIR=$SDK_DIR" >> $GITHUB_ENV

    - name: 准备编译环境
      run: |
        cd ${{ env.SDK_DIR }}
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: 修复Kconfig警告
      run: |
        cd ${{ env.SDK_DIR }}
        # 精确删除choice作用域内的default
        find . -name "*.in" -exec sed -i '/choice/,/endchoice/{
          /^\s*default/d
          /config\s\+[A-Z0-9_]\+$\s*default/s/\s*default.*//
        }' {} \;

    - name: 配置目标设备
      run: |
        cd ${{ env.SDK_DIR }}
        make defconfig
        
        # 追加核心配置
        cat >> .config << 'EOF'
        # 基础系统配置
        CONFIG_TARGET_ROOTFS_SQUASHFS=y
        CONFIG_PACKAGE_luci=y
        CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
        
        # 网络服务
        CONFIG_PACKAGE_dnsmasq=y
        CONFIG_PACKAGE_firewall=y
        CONFIG_PACKAGE_odhcpd=y
        
        # 打印服务
        CONFIG_PACKAGE_cups=y
        CONFIG_PACKAGE_avahi-daemon=y
        CONFIG_PACKAGE_kmod-usb-printer=y
        CONFIG_PACKAGE_kmod-usb2=y
        
        # 驱动支持
        CONFIG_PACKAGE_p910nd=y
        CONFIG_PACKAGE_splix=y
        EOF

    - name: 自定义固件设置
      run: |
        cd ${{ env.SDK_DIR }}
        export TERM=linux
        
        # 确保配置已生成
        make target/compile || make package/base-files/compile
        
        # 安全修改IP
        if [ -f "package/base-files/files/bin/config_generate" ]; then
          sed -i 's/192.168.1.1/192.168.2.1/g' package/base-files/files/bin/config_generate
        else
          echo "::warning::未找到config_generate，跳过IP修改"
        fi
        
        # 配置打印机服务发现
        mkdir -p files/etc/avahi/services
        cat > files/etc/avahi/services/cups-ipp.service << 'EOF'
        <?xml version="1.0" standalone='no'?>
        <!DOCTYPE service-group SYSTEM "avahi-service.dtd">
        <service-group>
          <name replace-wildcards="yes">%h打印机</name>
          <service>
            <type>_ipp._tcp</type>
            <port>631</port>
            <txt-record>rp=printers/Canon_MF4452</txt-record>
            <txt-record>note=Canon MF4452 on 360P2</txt-record>
            <txt-record>product=(Canon MF4452)</txt-record>
          </service>
        </service-group>
        EOF

    - name: 编译固件
      run: |
        cd ${{ env.SDK_DIR }}
        make -j$(nproc) V=s || {
          echo "首次编译失败，尝试清理后重试..."
          make clean
          make -j1 V=s
        }
        
        # 严格验证输出
        FIRMWARE_PATH="bin/ramips/openwrt-ramips-mt7628-360P2-squashfs-sysupgrade.bin"
        if [ ! -f "$FIRMWARE_PATH" ]; then
          echo "::error::固件生成失败，输出文件列表："
          ls -la bin/ramips/
          exit 1
        fi

    - name: 上传编译产物
      uses: actions/upload-artifact@v4
      with:
        name: 360P2-Printer-Firmware
        path: bin/ramips/openwrt-ramips-mt7628-360P2-squashfs-sysupgrade.bin
